<a href="https://colab.research.google.com/github/faro7ah/python_project/blob/main/intro_to_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('https://github.com/gumdropsteve/intro_to_machine_learning/raw/main/day_04/data/riyadh.csv')

In [3]:
df

                              ds  ... chefs_kitchen_bool
0     2021-01-20 04:14:08.745592  ...                NaN
1     2021-01-20 04:14:08.745592  ...                NaN
2     2021-01-20 04:14:08.745592  ...                NaN
3     2021-01-20 04:14:08.745592  ...                NaN
4     2021-01-20 04:14:08.745592  ...                NaN
...                          ...  ...                ...
6360  2021-01-26 05:12:03.778976  ...                NaN
6361  2021-01-26 05:12:03.778976  ...                NaN
6362  2021-01-26 05:12:03.778976  ...                NaN
6363  2021-01-26 05:12:03.778976  ...                NaN
6364  2021-01-26 05:12:03.778976  ...                NaN

[6365 rows x 40 columns]

In [4]:
df.location.unique()

array(['Riyadh', 'boutique hotel', 'الرياض', 'Al Kharj', 'بريدة',
       'Al Majmaah', 'Buraydah', 'Al-Muzahmiya', 'Unayzah', 'الغماس',
       'Riyadh ', 'Shaqra', 'Ad Dilam', 'aparthotel', 'SA',
       'Al Bukayriyah', 'serviced apartment', 'Al Bahah', 'المليداء',
       'Al-Kharj', 'Ad Diriyah', 'Al Qassim',
       'Kingdom of Saudi Arabia City', 'Thadiq', 'Az Zulfi', 'Rumah',
       'البرج', 'Riyadh Province', 'النماص', 'Hail', 'Al Ghat',
       'Al Duwadimi', 'Almuzahmiyah', 'القرينه'], dtype=object)

In [5]:
df.location.replace(['الرياض', 'Riyadh ', 'Riyadh Province'],'Riyadh', inplace =True)
df.location.replace(['بريدة', 'المليداء', 'Buraydah', 'Unayzah', 'الغماس', 'Al Bukayriyah'],'Al Qassim', inplace =True)
df.location.replace(['serviced apartment','Kingdom of Saudi Arabia City', 'aparthotel', 'boutique hotel', 'البرج'],'SA', inplace =True)
df.location.replace(['النماص'],'Al Namas', inplace =True)
df.location.replace(['القرينه'],'Al Gereena', inplace =True)

In [6]:
df.location.unique()

array(['Riyadh', 'SA', 'Al Kharj', 'Al Qassim', 'Al Majmaah',
       'Al-Muzahmiya', 'Shaqra', 'Ad Dilam', 'Al Bahah', 'Al-Kharj',
       'Ad Diriyah', 'Thadiq', 'Az Zulfi', 'Rumah', 'Al Namas', 'Hail',
       'Al Ghat', 'Al Duwadimi', 'Almuzahmiyah', 'Al Gereena'],
      dtype=object)

In [7]:
df.isnull().sum()

ds                            0
search_filter              1500
url                           0
title                         0
type                          0
location                      0
guests                     3333
bedrooms                      0
beds                       3333
is_studio                     0
baths                      1018
half_baths                 6339
shared_baths               6221
price                         0
avg_rating                 3165
n_reviews                  3165
gym_bool                   6070
wifi_bool                  3597
self_check_in_bool         5218
air_conditioning_bool      2058
pets_allowed_bool          5578
indoor_fireplace_bool      6229
hot_tub_bool               6186
free_parking_bool          4311
pool_bool                  5051
kitchen_bool               2070
breakfast_bool             6271
elevator_bool              5619
washer_bool                5494
dryer_bool                 6021
heating_bool               6365
waterfront_bool            6364
dishwasher_bool            6348
beachfront_bool            6354
ski_in_ski_out_bool        6365
terrace_bool               6365
sonos_sound_system_bool    6365
bbq_grill_bool             6365
hair_dryer_bool            6365
chefs_kitchen_bool         6365
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6365 entries, 0 to 6364
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ds                       6365 non-null   object
 1   search_filter            4865 non-null   object
 2   url                      6365 non-null   object
 3   title                    6365 non-null   object
 4   type                     6365 non-null   object
 5   location                 6365 non-null   object
 6   guests                   3032 non-null   float64
 7   bedrooms                 6365 non-null   int64
 8   beds                     3032 non-null   float64
 9   is_studio                6365 non-null   bool
 10  baths                    5347 non-null   float64
 11  half_baths               26 non-null     float64
 12  shared_baths             144 non-null    float64
 13  price                    6365 non-null   float64
 14  avg_rating               3200 non-null   float64
 15  n_reviews                3200 non-null   float64
 16  gym_bool                 295 non-null    object
 17  wifi_bool                2768 non-null   object
 18  self_check_in_bool       1147 non-null   object
 19  air_conditioning_bool    4307 non-null   object
 20  pets_allowed_bool        787 non-null    object
 21  indoor_fireplace_bool    136 non-null    object
 22  hot_tub_bool             179 non-null    object
 23  free_parking_bool        2054 non-null   object
 24  pool_bool                1314 non-null   object
 25  kitchen_bool             4295 non-null   object
 26  breakfast_bool           94 non-null     object
 27  elevator_bool            746 non-null    object
 28  washer_bool              871 non-null    object
 29  dryer_bool               344 non-null    object
 30  heating_bool             0 non-null      float64
 31  waterfront_bool          1 non-null      object
 32  dishwasher_bool          17 non-null     object
 33  beachfront_bool          11 non-null     object
 34  ski_in_ski_out_bool      0 non-null      float64
 35  terrace_bool             0 non-null      float64
 36  sonos_sound_system_bool  0 non-null      float64
 37  bbq_grill_bool           0 non-null      float64
 38  hair_dryer_bool          0 non-null      float64
 39  chefs_kitchen_bool       0 non-null      float64
dtypes: bool(1), float64(15), int64(1), object(23)
memory usage: 1.9+ MB

In [9]:
df.fillna(df.mean(), inplace=True)

In [10]:
df.search_filter.unique()

array(['iyadh', 'iyadh_super_hosts', 'iyadh_entire_homes',
       'iyadh_entire_home_super_hosts', 'iyadh_hotel_rooms',
       'iyadh_hotel_room_super_hosts', 'iyadh_private_rooms',
       'iyadh_shared_rooms', nan, 'super_hosts', 'entire_homes',
       'entire_home_super_hosts', 'hotel_rooms', 'hotel_room_super_hosts',
       'private_rooms', 'shared_rooms'], dtype=object)

In [11]:
df.search_filter.replace(['iyadh'],'Riyadh', inplace =True)

In [12]:
df['search_filter'].fillna('Riyadh', inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6365 entries, 0 to 6364
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ds                       6365 non-null   object
 1   search_filter            6365 non-null   object
 2   url                      6365 non-null   object
 3   title                    6365 non-null   object
 4   type                     6365 non-null   object
 5   location                 6365 non-null   object
 6   guests                   6365 non-null   float64
 7   bedrooms                 6365 non-null   int64
 8   beds                     6365 non-null   float64
 9   is_studio                6365 non-null   bool
 10  baths                    6365 non-null   float64
 11  half_baths               6365 non-null   float64
 12  shared_baths             6365 non-null   float64
 13  price                    6365 non-null   float64
 14  avg_rating               6365 non-null   float64
 15  n_reviews                6365 non-null   float64
 16  gym_bool                 6365 non-null   object
 17  wifi_bool                6365 non-null   object
 18  self_check_in_bool       6365 non-null   object
 19  air_conditioning_bool    6365 non-null   object
 20  pets_allowed_bool        6365 non-null   object
 21  indoor_fireplace_bool    6365 non-null   object
 22  hot_tub_bool             6365 non-null   object
 23  free_parking_bool        6365 non-null   object
 24  pool_bool                6365 non-null   object
 25  kitchen_bool             6365 non-null   object
 26  breakfast_bool           6365 non-null   object
 27  elevator_bool            6365 non-null   object
 28  washer_bool              6365 non-null   object
 29  dryer_bool               6365 non-null   object
 30  heating_bool             0 non-null      float64
 31  waterfront_bool          6365 non-null   object
 32  dishwasher_bool          6365 non-null   object
 33  beachfront_bool          6365 non-null   object
 34  ski_in_ski_out_bool      0 non-null      float64
 35  terrace_bool             0 non-null      float64
 36  sonos_sound_system_bool  0 non-null      float64
 37  bbq_grill_bool           0 non-null      float64
 38  hair_dryer_bool          0 non-null      float64
 39  chefs_kitchen_bool       0 non-null      float64
dtypes: bool(1), float64(15), int64(1), object(23)
memory usage: 1.9+ MB

In [14]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

vec.fit_transform(data)[0]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [15]:
vec.feature_names_

['type=Camper/RV',
 'type=Campsite',
 'type=Dome house',
 'type=Earth house',
 'type=Entire apartment',
 'type=Entire chalet',
 'type=Entire condominium',
 'type=Entire cottage',
 'type=Entire guest suite',
 'type=Entire guesthouse',
 'type=Entire house',
 'type=Entire loft',
 'type=Entire place',
 'type=Entire serviced apartment',
 'type=Entire villa',
 'type=Farm stay',
 'type=Hotel room',
 'type=Hut',
 'type=Private room',
 'type=Resort room',
 'type=Room',
 'type=Shared room',
 'type=Tent',
 'type=Tiny house']

In [16]:
vec.fit_transform(data)[-5:]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0]])

In [17]:
pd.DataFrame(df['type'])

                           type
0                 Entire chalet
1                 Entire chalet
2              Entire apartment
3                 Entire chalet
4              Entire apartment
...                         ...
6360  Entire serviced apartment
6361           Entire apartment
6362           Entire apartment
6363           Entire apartment
6364                Resort room

[6365 rows x 1 columns]

In [18]:
len(df['type'].unique())

24

In [19]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

t = vec.fit_transform(data)
names = vec.feature_names_

pd.DataFrame(t, columns=names)

      type=Camper/RV  type=Campsite  ...  type=Tent  type=Tiny house
0                  0              0  ...          0                0
1                  0              0  ...          0                0
2                  0              0  ...          0                0
3                  0              0  ...          0                0
4                  0              0  ...          0                0
...              ...            ...  ...        ...              ...
6360               0              0  ...          0                0
6361               0              0  ...          0                0
6362               0              0  ...          0                0
6363               0              0  ...          0                0
6364               0              0  ...          0                0

[6365 rows x 24 columns]

In [23]:
pd.get_dummies(df['type'])

      Camper/RV  Campsite  Dome house  ...  Shared room  Tent  Tiny house
0             0         0           0  ...            0     0           0
1             0         0           0  ...            0     0           0
2             0         0           0  ...            0     0           0
3             0         0           0  ...            0     0           0
4             0         0           0  ...            0     0           0
...         ...       ...         ...  ...          ...   ...         ...
6360          0         0           0  ...            0     0           0
6361          0         0           0  ...            0     0           0
6362          0         0           0  ...            0     0           0
6363          0         0           0  ...            0     0           0
6364          0         0           0  ...            0     0           0

[6365 rows x 24 columns]

In [21]:
df

                              ds  ... chefs_kitchen_bool
0     2021-01-20 04:14:08.745592  ...                NaN
1     2021-01-20 04:14:08.745592  ...                NaN
2     2021-01-20 04:14:08.745592  ...                NaN
3     2021-01-20 04:14:08.745592  ...                NaN
4     2021-01-20 04:14:08.745592  ...                NaN
...                          ...  ...                ...
6360  2021-01-26 05:12:03.778976  ...                NaN
6361  2021-01-26 05:12:03.778976  ...                NaN
6362  2021-01-26 05:12:03.778976  ...                NaN
6363  2021-01-26 05:12:03.778976  ...                NaN
6364  2021-01-26 05:12:03.778976  ...                NaN

[6365 rows x 40 columns]

In [25]:
pd.get_dummies(df['type']).head(40), df['type'].head(40)

(    Camper/RV  Campsite  Dome house  ...  Shared room  Tent  Tiny house
 0           0         0           0  ...            0     0           0
 1           0         0           0  ...            0     0           0
 2           0         0           0  ...            0     0           0
 3           0         0           0  ...            0     0           0
 4           0         0           0  ...            0     0           0
 5           0         0           0  ...            0     0           0
 6           0         0           0  ...            0     0           0
 7           0         0           0  ...            0     0           0
 8           0         0           0  ...            0     0           0
 9           0         0           0  ...            0     0           0
 10          0         0           0  ...            0     0           0
 11          0         0           0  ...            0     0           0
 12          0         0           0  ...            0     0           0
 13          0         0           0  ...            0     0           0
 14          0         0           0  ...            0     0           0
 15          0         0           0  ...            0     0           0
 16          0         0           0  ...            0     0           0
 17          0         0           0  ...            0     0           0
 18          0         0           0  ...            0     0           0
 19          0         0           0  ...            0     0           0
 20          0         0           0  ...            0     0           0
 21          0         0           0  ...            0     0           0
 22          0         0           0  ...            0     0           0
 23          0         0           0  ...            0     0           0
 24          0         0           0  ...            0     0           0
 25          0         0           0  ...            0     0           0
 26          0         0           0  ...            0     0           0
 27          0         0           0  ...            0     0           0
 28          0         0           0  ...            0     0           0
 29          0         0           0  ...            0     0           0
 30          0         0           0  ...            0     0           0
 31          0         0           0  ...            0     0           0
 32          0         0           0  ...            0     0           0
 33          0         0           0  ...            0     0           0
 34          0         0           0  ...            0     0           0
 35          0         0           0  ...            0     0           0
 36          0         0           0  ...            0     0           1
 37          0         0           0  ...            0     0           0
 38          0         0           0  ...            0     0           0
 39          0         0           0  ...            0     0           0

 [40 rows x 24 columns], 0          Entire chalet
 1          Entire chalet
 2       Entire apartment
 3          Entire chalet
 4       Entire apartment
 5       Entire apartment
 6          Entire chalet
 7       Entire apartment
 8                   Room
 9       Entire apartment
 10      Entire apartment
 11      Entire apartment
 12    Entire condominium
 13      Entire apartment
 14      Entire apartment
 15      Entire apartment
 16      Entire apartment
 17      Entire apartment
 18    Entire guest suite
 19          Entire villa
 20      Entire apartment
 21      Entire apartment
 22      Entire apartment
 23      Entire apartment
 24      Entire apartment
 25          Entire house
 26      Entire apartment
 27      Entire apartment
 28          Private room
 29      Entire apartment
 30      Entire apartment
 31      Entire apartment
 32          Private room
 33      Entire apartment
 34      Entire apartment
 35      Entire apartment
 36            Tiny house
 37          Entire house
 38      Entire apartment
 39          Private room
 Name: type, dtype: object)

In [27]:
pd.get_dummies(df['type']).head(40)

    Camper/RV  Campsite  Dome house  ...  Shared room  Tent  Tiny house
0           0         0           0  ...            0     0           0
1           0         0           0  ...            0     0           0
2           0         0           0  ...            0     0           0
3           0         0           0  ...            0     0           0
4           0         0           0  ...            0     0           0
5           0         0           0  ...            0     0           0
6           0         0           0  ...            0     0           0
7           0         0           0  ...            0     0           0
8           0         0           0  ...            0     0           0
9           0         0           0  ...            0     0           0
10          0         0           0  ...            0     0           0
11          0         0           0  ...            0     0           0
12          0         0           0  ...            0     0           0
13          0         0           0  ...            0     0           0
14          0         0           0  ...            0     0           0
15          0         0           0  ...            0     0           0
16          0         0           0  ...            0     0           0
17          0         0           0  ...            0     0           0
18          0         0           0  ...            0     0           0
19          0         0           0  ...            0     0           0
20          0         0           0  ...            0     0           0
21          0         0           0  ...            0     0           0
22          0         0           0  ...            0     0           0
23          0         0           0  ...            0     0           0
24          0         0           0  ...            0     0           0
25          0         0           0  ...            0     0           0
26          0         0           0  ...            0     0           0
27          0         0           0  ...            0     0           0
28          0         0           0  ...            0     0           0
29          0         0           0  ...            0     0           0
30          0         0           0  ...            0     0           0
31          0         0           0  ...            0     0           0
32          0         0           0  ...            0     0           0
33          0         0           0  ...            0     0           0
34          0         0           0  ...            0     0           0
35          0         0           0  ...            0     0           0
36          0         0           0  ...            0     0           1
37          0         0           0  ...            0     0           0
38          0         0           0  ...            0     0           0
39          0         0           0  ...            0     0           0

[40 rows x 24 columns]

In [28]:
df.columns

Index(['ds', 'search_filter', 'url', 'title', 'type', 'location', 'guests',
       'bedrooms', 'beds', 'is_studio', 'baths', 'half_baths', 'shared_baths',
       'price', 'avg_rating', 'n_reviews', 'gym_bool', 'wifi_bool',
       'self_check_in_bool', 'air_conditioning_bool', 'pets_allowed_bool',
       'indoor_fireplace_bool', 'hot_tub_bool', 'free_parking_bool',
       'pool_bool', 'kitchen_bool', 'breakfast_bool', 'elevator_bool',
       'washer_bool', 'dryer_bool', 'heating_bool', 'waterfront_bool',
       'dishwasher_bool', 'beachfront_bool', 'ski_in_ski_out_bool',
       'terrace_bool', 'sonos_sound_system_bool', 'bbq_grill_bool',
       'hair_dryer_bool', 'chefs_kitchen_bool'],
      dtype='object')

In [29]:
df.title

0                                    Modern CHALET
1                           ALQIRWAN modern chalet
2       Fully Furnished Apartment With One Bedroom
3                  Marvelous Chalet شاليه مارفيلوس
4         FENDI Designed luxury sky view apartment
                           ...
6360                                  الركن البعيد
6361                        شقه مدخل خاص حي الملقا
6362                  Modern apartment in Alnarjis
6363                    Damac Fendi Tower - Riyadh
6364            شاليه رونزالاند رقم 9 المطل الغربي
Name: title, Length: 6365, dtype: object

In [45]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

d = vec.fit_transform(data)

type_df = pd.DataFrame(d, columns=vec.feature_names_)
type_df.tail(3)

      type=Camper/RV  type=Campsite  ...  type=Tent  type=Tiny house
6362               0              0  ...          0                0
6363               0              0  ...          0                0
6364               0              0  ...          0                0

[3 rows x 24 columns]

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
X = vec.fit_transform(df.title)

title_df = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

In [44]:
title_df

      0558052228  20  21  2bd  2bedroom  ...  يونيك  ١٦٠  ٢دورين  ٨دقائق  ڤيلا
0              0   0   0    0         0  ...      0    0       0       0     0
1              0   0   0    0         0  ...      0    0       0       0     0
2              0   0   0    0         0  ...      0    0       0       0     0
3              0   0   0    0         0  ...      0    0       0       0     0
4              0   0   0    0         0  ...      0    0       0       0     0
...          ...  ..  ..  ...       ...  ...    ...  ...     ...     ...   ...
6360           0   0   0    0         0  ...      0    0       0       0     0
6361           0   0   0    0         0  ...      0    0       0       0     0
6362           0   0   0    0         0  ...      0    0       0       0     0
6363           0   0   0    0         0  ...      0    0       0       0     0
6364           0   0   0    0         0  ...      0    0       0       0     0

[6365 rows x 752 columns]

In [32]:
import numpy as np

np.sum(pd.DataFrame(X.toarray(), columns=vec.get_feature_names()))

0558052228     7
20             1
21             2
2bd           28
2bedroom      41
              ..
يونيك         15
١٦٠            7
٢دورين        11
٨دقائق        13
ڤيلا          11
Length: 752, dtype: int64

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
sample = df['title']

vec = TfidfVectorizer()

X = vec.fit_transform(sample)

Tfid_df = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

In [43]:
Tfid_df

      0558052228   20   21  2bd  2bedroom  ...  يونيك  ١٦٠  ٢دورين  ٨دقائق  ڤيلا
0            0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
1            0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
2            0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
3            0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
4            0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
...          ...  ...  ...  ...       ...  ...    ...  ...     ...     ...   ...
6360         0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
6361         0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
6362         0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
6363         0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0
6364         0.0  0.0  0.0  0.0       0.0  ...    0.0  0.0     0.0     0.0   0.0

[6365 rows x 752 columns]

In [46]:
big_df = pd.concat([df, type_df, Tfid_df], axis=1)

big_df

                              ds search_filter  ... ٨دقائق ڤيلا
0     2021-01-20 04:14:08.745592        Riyadh  ...    0.0  0.0
1     2021-01-20 04:14:08.745592        Riyadh  ...    0.0  0.0
2     2021-01-20 04:14:08.745592        Riyadh  ...    0.0  0.0
3     2021-01-20 04:14:08.745592        Riyadh  ...    0.0  0.0
4     2021-01-20 04:14:08.745592        Riyadh  ...    0.0  0.0
...                          ...           ...  ...    ...  ...
6360  2021-01-26 05:12:03.778976  shared_rooms  ...    0.0  0.0
6361  2021-01-26 05:12:03.778976  shared_rooms  ...    0.0  0.0
6362  2021-01-26 05:12:03.778976  shared_rooms  ...    0.0  0.0
6363  2021-01-26 05:12:03.778976  shared_rooms  ...    0.0  0.0
6364  2021-01-26 05:12:03.778976  shared_rooms  ...    0.0  0.0

[6365 rows x 816 columns]

In [39]:
t = pd.DataFrame()

t['price_per_bed'] = df['beds'] / df['price']

t

      price_per_bed
0          0.009728
1          0.000000
2          0.014908
3          0.000000
4          0.006042
...             ...
6360       0.018943
6361       0.011828
6362       0.028630
6363       0.005956
6364       0.069767

[6365 rows x 1 columns]